import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/Footer";
import Navbar from "./components/Navbar";
import { CartProvider } from "./CartContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "7th Street Burger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CartProvider>
        <html lang="en" className="scroll-smooth">
          <body
            className={`${poppins.className} antialiased w-full flex items-center justify-center bg-red-500 `}
          >
            <div className="w-[100%] justify-between relative min-h-screen pb-[220px] bg-[#8B403C]">
              <Navbar /> {children} <Footer />
            </div>
          </body>
        </html>
      </CartProvider>
    </>
  );
}
